// Assemble the extension's content scripts from the shared instrument bundle.
//
// The whole reason this is a build step and not a checked-in file: boot.main.js
// must stay byte-identical in its instruments (rrweb + tick + motion + hud) to
// what the CLI injects, or the extension and the CLI would silently diverge and
// a bug fixed in one would live on in the other. bootScript() is the single
// source; this only swaps the transport (Playwright binding -> CustomEvent) and
// turns the HUD on, because a human is always the one being recorded here.
//
// annotate.iso.js is built the same way and for the same reason: it carries
// lib/selector.js, so the selector a comment reports and the selector a mark
// records come from one file even though they run in different worlds.
//
//   node build.mjs
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { bootScript, lensScript } from '../lib/record.mjs'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const LIB = path.resolve(HERE, '..', 'lib')
const HEAD = '// GENERATED by chrome-ext/build.mjs from ../lib — do not edit by hand.'

/** @param {string} name @param {string} body */
const write = (name, body) => {
  const out = path.join(HERE, 'src', name)
  fs.writeFileSync(out, `${HEAD}\n${body}\n`)
  console.log(`wrote ${path.relative(HERE, out)}  ${(fs.statSync(out).size / 1024).toFixed(0)}KB`)
}

write('boot.main.js', bootScript({ mask: true, hud: true, transport: 'event' }))
// The lens, for every frame. boot.main.js goes to the top frame only, because
// the recorder must not be duplicated; this one goes everywhere, because a ring
// can only be drawn by the frame that owns the coordinates.
write('lens.main.js', lensScript())
// Order matters: the selector first (tick.js and the overlay share it), then
// the lens that draws every ring either surface puts on the page, then the
// behaviour that uses both. lens.js is in this bundle AND in boot.main.js —
// one file, evaluated once per world, the same arrangement selector.js has.
export const ANNOTATE_PARTS = ['selector.js', 'lens.js', 'annotate.js']
write('annotate.iso.js', ANNOTATE_PARTS
  .map((f) => fs.readFileSync(path.join(LIB, f), 'utf8'))
  .join('\n;'))
