// Assemble the MAIN-world content script from the shared instrument bundle.
//
// The whole reason this is a build step and not a checked-in file: boot.main.js
// must stay byte-identical in its instruments (rrweb + tick + motion + hud) to
// what the CLI injects, or the extension and the CLI would silently diverge and
// a bug fixed in one would live on in the other. bootScript() is the single
// source; this only swaps the transport (Playwright binding -> CustomEvent) and
// turns the HUD on, because a human is always the one being recorded here.
//
//   node build.mjs
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { bootScript } from '../lib/record.mjs'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const boot = bootScript({ mask: true, hud: true, transport: 'event' })
const out = path.join(HERE, 'src', 'boot.main.js')
fs.writeFileSync(out, `// GENERATED by chrome-ext/build.mjs from ../lib — do not edit by hand.\n${boot}\n`)
console.log(`wrote ${path.relative(HERE, out)}  ${(fs.statSync(out).size / 1024).toFixed(0)}KB`)
