// Assemble the extension's content scripts from the shared instrument bundle.
//
// The whole reason this is a build step and not a checked-in file: boot.main.js
// must stay byte-identical in its instruments (rrweb + tick + motion + hud) to
// what the CLI injects, or the extension and the CLI would silently diverge and
// a bug fixed in one would live on in the other. bootScript() is the single
// source; this only swaps the transport (Playwright binding -> CustomEvent) and
// turns the HUD on, because a human is always the one being recorded here.
//
// annotate.iso.js is built the same way and for the same reason: it carries
// lib/selector.js, so the selector a comment reports and the selector a mark
// records come from one file even though they run in different worlds.
//
//   node build.mjs
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { bootScript } from '../lib/record.mjs'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const LIB = path.resolve(HERE, '..', 'lib')
const HEAD = '// GENERATED by chrome-ext/build.mjs from ../lib — do not edit by hand.'

/** @param {string} name @param {string} body */
const write = (name, body) => {
  const out = path.join(HERE, 'src', name)
  fs.writeFileSync(out, `${HEAD}\n${body}\n`)
  console.log(`wrote ${path.relative(HERE, out)}  ${(fs.statSync(out).size / 1024).toFixed(0)}KB`)
}

write('boot.main.js', bootScript({ mask: true, hud: true, transport: 'event' }))
write('annotate.iso.js', [
  fs.readFileSync(path.join(LIB, 'selector.js'), 'utf8'),
  fs.readFileSync(path.join(LIB, 'annotate.js'), 'utf8'),
].join('\n;'))
