// Phase 1: dump real selectors from the RUNNING app, with visibility.
// Writing cases.csv from source code is how you bind to hidden twins.
import fs from 'node:fs'
import path from 'node:path'
const HERE = path.dirname(new URL(import.meta.url).pathname)
let chromium
try { ({ chromium } = await import('playwright')) } catch {
  console.error(`\nweb-qa: dependencies are not installed.\n  cd ${path.join(HERE, '..').replace(process.env.HOME, '~')} && pnpm install\n`)
  process.exit(3)
}

const cfg   = JSON.parse(fs.readFileSync(process.env.CONFIG ?? 'qa.config.json', 'utf8'))
const BASE  = process.env.BASE ?? cfg.base
const OUT   = cfg.out ?? 'out'
const ROUTES = process.argv.slice(2).length ? process.argv.slice(2) : (cfg.routes ?? ['/'])

const browser = await chromium.launch()
const ctx = await browser.newContext({ viewport: cfg.viewport ?? { width: 1280, height: 800 } })
const page = await ctx.newPage()

for (const [action, target, value] of cfg.auth?.steps ?? []) {
  if (action === 'goto') await page.goto(BASE + target, { waitUntil: 'domcontentloaded' })
  else if (action === 'fill') await page.fill(target, value)
  else if (action === 'click') await page.click(target)
  else if (action === 'assert_url') await page.waitForURL(u => !u.href.includes(value.replace(/^!/, '')), { timeout: 15000 }).catch(() => {})
}

const out = [`# DOM map — ${BASE}`, '', `Generated by web-qa introspect. \`vis\` = actually visible.`, '']

for (const route of ROUTES) {
  const res = await page.goto(BASE + route, { waitUntil: 'domcontentloaded' }).catch(() => null)
  await page.waitForLoadState('networkidle').catch(() => {})
  out.push(`## ${route}  →  ${res ? res.status() : 'no response'}  (${page.url().replace(BASE, '')})`, '')

  const dump = await page.evaluate(() => {
    const vis = e => !!(e.offsetWidth || e.offsetHeight || e.getClientRects().length)
    const label = e => e.getAttribute('aria-label') || e.getAttribute('placeholder') ||
                       e.getAttribute('name') || (e.textContent || '').trim().slice(0, 40)
    const list = (sel, fn) => [...document.querySelectorAll(sel)].map(fn)
    return {
      forms: list('form', f => ({
        vis: vis(f),
        fields: [...f.querySelectorAll('[name]')].map(n => n.getAttribute('name')).filter(n => !n.startsWith('$')).slice(0, 12),
        submit: [...f.querySelectorAll('button')].map(b => (b.textContent || '').trim()).slice(0, 4),
      })),
      buttons: list('button', b => ({ vis: vis(b), type: b.getAttribute('type') || '(none=submit)', text: (b.textContent || '').trim().slice(0, 32) })),
      inputs: list('input,select,textarea', i => ({ vis: vis(i), tag: i.tagName.toLowerCase(), type: i.getAttribute('type') || '', name: i.getAttribute('name') || '', aria: i.getAttribute('aria-label') || '' })),
      landmarks: list('[aria-label],[data-testid],[role=dialog],table', e => ({ vis: vis(e), tag: e.tagName.toLowerCase(), key: e.getAttribute('data-testid') ? `[data-testid="${e.getAttribute('data-testid')}"]` : e.getAttribute('aria-label') ? `${e.tagName.toLowerCase()}[aria-label="${e.getAttribute('aria-label')}"]` : e.tagName.toLowerCase() })),
    }
  })

  const tbl = (title, head, rows) => {
    if (!rows.length) return
    out.push(`### ${title}`, '', `| ${head.join(' | ')} |`, `|${head.map(() => '---').join('|')}|`,
             ...rows.map(r => `| ${r.join(' | ')} |`), '')
  }
  tbl('forms', ['vis', 'fields', 'buttons'],
      dump.forms.map((f, i) => [f.vis ? 'yes' : '**NO**', '`' + (f.fields.join(', ') || '-') + '`', f.submit.join(' / ') || '-']))
  tbl('buttons', ['vis', 'type', 'text'],
      dump.buttons.map(b => [b.vis ? 'yes' : '**NO**', '`' + b.type + '`', b.text || '-']))
  tbl('inputs', ['vis', 'selector', 'aria-label'],
      dump.inputs.filter(i => i.name || i.aria).map(i => [i.vis ? 'yes' : '**NO**',
        '`' + (i.name && !i.name.startsWith('$') ? `${i.tag}[name=${i.name}]` : `${i.tag}[aria-label="${i.aria}"]`) + '`', i.aria || '-']))
  tbl('landmarks', ['vis', 'selector'],
      [...new Map(dump.landmarks.map(l => [l.key, l])).values()].map(l => [l.vis ? 'yes' : '**NO**', '`' + l.key + '`']))

  // the trap this file exists to prevent
  const dupes = dump.buttons.filter(b => b.type === '(none=submit)' && b.vis)
  const hidden = dump.forms.filter(f => !f.vis).length + dump.buttons.filter(b => !b.vis).length
  if (hidden) out.push(`> ${hidden} hidden form/button element(s) on this route. Never use a bare \`form\` or \`button[type=submit]\` selector here — scope it, e.g. \`form:has(input[name=X]) button\`.`, '')
  if (dupes.length) out.push(`> ${dupes.length} visible \`<button>\` without a \`type\` attribute — these submit but do NOT match \`button[type=submit]\`. Use \`button:has-text("…")\`.`, '')
}

await browser.close()
fs.mkdirSync(OUT, { recursive: true })
fs.writeFileSync(`${OUT}/dom-map.md`, out.join('\n'))
console.log(`${OUT}/dom-map.md — ${ROUTES.length} routes`)
